### ISSUE TITLE
Support for python3

### ISSUE THREAD

**Issue by richardm47** [zhiyajun11/happybase-kerberos-patch#1]
Is there any version that supports this in python 3.5+ ?

**Comment by normal-cock** [comment]
It doesn't support python 3.5+ now. Sometime in future it will  will support python3 though :) .

**Comment by normal-cock** [comment]
@richardm47 
Now python3 is supported. Please update to newest version 0.1.4 to use in python3. 
`pip install -U git+https://github.com/normal-cock/happybase-kerberos-patch.git@0.1.4`
