### ISSUE TITLE
“readall” error

### ISSUE THREAD

**Issue by littlebear-xbz** [zhiyajun11/happybase-kerberos-patch#9]
I found that the ”thriftpy2“ latest version not have function “readall”， so you run the demo first line，you will get error.
`>>> from happybase_kerberos_patch import KerberosConnection, KerberosConnectionPool
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda2/envs/py37/lib/python3.7/site-packages/happybase_kerberos_patch.py", line 13, in <module>
    from thriftpy2.transport import TBufferedTransport, TFramedTransport, TSocket, TTransportBase, TTransportException, readall
ImportError: cannot import name 'readall' from 'thriftpy2.transport' `

And you could solve it by set the thriftpy2 version, like
`pip install thriftpy2==0.4.8`

Hope author could solve this once and for all.
By the way , I love this project, it helped me.
Thanks.

**Comment by normal-cock** [comment]
Hi xbz, thanks for your feedback and solution. It would be very nice if you could submit a pull request for this issue. I think the version limit of `thriftpy2` could be placed in `install_requires` in `setup.py` and just before `happybase`. Could you do that? @littlebear-xbz

**Comment by littlebear-xbz** [comment]
Of course no problem , I rasied a pull request #10  for it .

**Comment by normal-cock** [comment]
Thanks for you contribution. The fix of this issue has been release on 0.1.5.
